version: '3.9'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .dev.env

    ports:
      - "8000:5432"
  app:
    build: ..
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .dev.env
    ports:
      - "80:80"